import{conceptModal,gameResultsPayload,questionPayload,reviewPayload,updateSearchModal}from"./ui.mjs";import{applyChoice,findNode,isReady,nextNewGameQuestion,nextUpdateQuestion}from"../wizard/engine.mjs";
function modeForCommand(n){return{"new-game":"NEW_GAME","new-game-collaborative":"NEW_GAME_COLLABORATIVE","update-game":"UPDATE_GAME","update-game-collaborative":"UPDATE_GAME_COLLABORATIVE"}[n];}function eph(m){return!m.endsWith("_COLLABORATIVE");}function editable(p){const{ephemeral,...rest}=p;return rest;}
function leadingChoice(session,node){const votes=session.votes?.[node.id]||{};let best=null,count=0,tie=false;for(const choice of node.choices){const c=votes[choice.id]?.length||0;if(c>count){best=choice;count=c;tie=false;}else if(c>0&&c===count)tie=true;}return tie?null:best;}
export function createRouter({sessions,requests,registry,config,logger=console}){async function assertChannel(i){if(config.channelId&&i.channelId!==config.channelId){await i.reply({content:"Use the configured NexusArcade Builder channel for this command.",ephemeral:true});return false;}return true;}
async function startNew(i,mode,concept){if(!concept)return i.showModal(conceptModal(mode));const s=await sessions.create({mode,ownerUserId:i.user.id,concept});const n=nextNewGameQuestion(s.profile,s.answeredQuestions);s.currentQuestion=n?.id||null;await sessions.save(s);return i.reply(n?questionPayload(s,n,eph(mode)):reviewPayload(s,isReady(s),eph(mode)));}
async function startUpdate(i,mode,query,change=null){if(!query||!change)return i.showModal(updateSearchModal(mode));const games=registry.search(query);if(!games.length)return i.reply({content:"No matching games are registered yet. Add the game to config/games.json first.",ephemeral:eph(mode)});const s=await sessions.create({mode,ownerUserId:i.user.id,gameId:games.length===1?games[0].gameId:null});s.profile.requestedChange=change;if(games.length>1){await sessions.save(s);return i.reply(gameResultsPayload(s,games,eph(mode)));}const n=nextUpdateQuestion(s.profile,s.answeredQuestions);s.currentQuestion=n?.id||null;await sessions.save(s);return i.reply(questionPayload(s,n,eph(mode)));}
return async function route(i){try{if(i.isChatInputCommand()){if(!(await assertChannel(i)))return;const mode=modeForCommand(i.commandName);if(!mode)return;if(mode.startsWith("NEW_GAME"))return startNew(i,mode,i.options.getString("concept"));return startUpdate(i,mode,i.options.getString("game"),i.options.getString("change"));}
if(i.isModalSubmit()&&i.customId.startsWith("nab:concept:"))return startNew(i,i.customId.split(":")[2],i.fields.getTextInputValue("concept"));
if(i.isModalSubmit()&&i.customId.startsWith("nab:game-search:"))return startUpdate(i,i.customId.split(":")[2],i.fields.getTextInputValue("query"),i.fields.getTextInputValue("change"));
if(i.isStringSelectMenu()&&i.customId.startsWith("nab:game:")){const id=i.customId.split(":")[2];let s=sessions.get(id);if(!s)return i.reply({content:"That Builder session is no longer active.",ephemeral:true});if(i.user.id!==s.ownerUserId)return i.reply({content:"Only the person who started this search can choose the game.",ephemeral:true});s=await sessions.mutate(id,d=>{d.gameId=i.values[0];d.profile.gameId=i.values[0];return d;});const n=nextUpdateQuestion(s.profile,s.answeredQuestions);s.currentQuestion=n?.id||null;await sessions.save(s);return i.update(editable(questionPayload(s,n,eph(s.mode))));}
if(!i.isButton()||!i.customId.startsWith("nab:"))return;const parts=i.customId.split(":"),action=parts[1],id=parts[2];let s=sessions.get(id);if(!s)return i.reply({content:"That Builder session is no longer active.",ephemeral:true});
if(action==="join"){s=await sessions.join(id,i.user.id);const n=findNode(s,s.currentQuestion);return i.update(editable(questionPayload(s,n,false)));}
if(action==="q"){const node=findNode(s,parts[3]),choice=node?.choices.find(x=>x.id===parts[4]);if(!sessions.canMutate(s,i.user.id))return i.reply({content:s.collaborative?"Join this shared session before contributing.":"This is another user's private Builder session.",ephemeral:true});if(!node||!choice)return i.reply({content:"That choice is no longer valid.",ephemeral:true});if(s.collaborative){s=await sessions.mutate(id,d=>{d.votes[node.id]||={};for(const key of Object.keys(d.votes[node.id]))d.votes[node.id][key]=d.votes[node.id][key].filter(u=>u!==i.user.id);d.votes[node.id][choice.id]||=[];d.votes[node.id][choice.id].push(i.user.id);return d;});return i.update(editable(questionPayload(s,node,false)));}s=await sessions.mutate(id,d=>applyChoice(d,node,choice,i.user.id));const next=nextNewGameQuestion(s.profile,s.answeredQuestions);s.currentQuestion=next?.id||null;await sessions.save(s);return i.update(editable(next?questionPayload(s,next,true):reviewPayload(s,isReady(s),true)));}
if(action==="lock"){if(i.user.id!==s.ownerUserId)return i.reply({content:"Only the session owner can lock a collaborative answer.",ephemeral:true});const node=findNode(s,parts[3]),choice=node&&leadingChoice(s,node);if(!choice)return i.reply({content:"There is no single leading answer yet. Break the tie with another vote.",ephemeral:true});s=await sessions.mutate(id,d=>applyChoice(d,node,choice,i.user.id));delete s.votes[node.id];const next=s.mode.startsWith("NEW_GAME")?nextNewGameQuestion(s.profile,s.answeredQuestions):nextUpdateQuestion(s.profile,s.answeredQuestions);s.currentQuestion=next?.id||null;await sessions.save(s);return i.update(editable(next?questionPayload(s,next,false):reviewPayload(s,isReady(s),false)));}
if(action==="submit"){if(i.user.id!==s.ownerUserId)return i.reply({content:"Only the session owner can submit the final request.",ephemeral:true});if(!isReady(s))return i.reply({content:"This request still has required gaps. Continue the guided questions first.",ephemeral:true});const r=await requests.submit(s);await sessions.mutate(id,d=>{d.state="SUBMITTED";return d;});logger.info?.(`[${new Date().toISOString()}] request ${r.id} created`);return i.update({content:`✅ **${r.id} created** · ${r.type} · Status: OPEN`,embeds:[],components:[]});}}
catch(error){logger.error?.(error);const p={content:"The Builder hit a recoverable error. Confirmed requests were not deleted.",ephemeral:true};if(i.deferred||i.replied)return i.followUp(p).catch(()=>{});return i.reply(p).catch(()=>{});}};}
