import {readFile,writeFile,mkdir,readdir,copyFile,stat} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {hash} from './model.mjs';
export const root=path.dirname(fileURLToPath(import.meta.url)),experiments=path.resolve(root,'../NexusArcade-Experiments');
async function files(dir){let out=[];for(const e of await readdir(dir,{withFileTypes:true})){const f=path.join(dir,e.name);if(e.isDirectory())out.push(...await files(f));else out.push(f);}return out.sort();}
export async function fingerprint(){const roots=['text-policy.mjs','scene-spec.mjs','scene-run.mjs','scene-review.mjs','scene-player.mjs','assembly.mjs','factory.mjs','improvement.mjs','catalog.mjs','catalog-compiler.mjs','domain-bindings.json','pilot-spec.mjs','pilot-options.json','pilot-player.mjs','pilot-review.mjs','pilot-run.mjs','player.mjs','game-shell.html','composition.mjs','model.mjs','harness.mjs','review3d.mjs','lessons.json'];let list=roots.map(f=>path.join(root,f));list.push(...await files(path.join(root,'kits')),...await files(path.join(root,'vendor')));return hash(Buffer.concat(await Promise.all(list.map(async f=>Buffer.from(path.relative(root,f)+'\n'+await readFile(f,'utf8'))))));}
export async function build(c,id){const upstream=JSON.parse(await readFile(path.join(root,'vendor/nexusengine/UPSTREAM.json')));for(const [f,digest] of Object.entries(upstream.files)){if(hash(await readFile(path.join(root,'vendor/nexusengine',f)))!==digest)throw Error('NexusEngine dependency mismatch: '+f);}const sourceHash=await fingerprint(),dest=path.join(experiments,'.runtime',sourceHash);try{await stat(path.join(dest,'ready'));}catch{await mkdir(dest,{recursive:true});for(const f of [path.join(root,'player.mjs'),path.join(root,'pilot-player.mjs'),path.join(root,'scene-player.mjs'),...await files(path.join(root,'kits')),...await files(path.join(root,'vendor'))]){const target=path.join(dest,path.relative(root,f));await mkdir(path.dirname(target),{recursive:true});await copyFile(f,target);}const three=path.resolve(root,'../node_modules/three');await mkdir(path.join(dest,'vendor/three'),{recursive:true});const lock=JSON.parse(await readFile(path.resolve(root,'../generation/builders/dependencies.lock.json')));for(const f of lock.three.files){const bytes=await readFile(path.join(three,'build',f.path));if(hash(bytes)!==f.sha256)throw Error('Three.js dependency mismatch');await writeFile(path.join(dest,'vendor/three',f.path),bytes);}await copyFile(path.join(three,'LICENSE'),path.join(dest,'vendor/three/LICENSE'));const manifest={};for(const f of await files(dest))manifest[path.relative(dest,f)]=hash(await readFile(f));await writeFile(path.join(dest,'manifest.json'),JSON.stringify(manifest));await writeFile(path.join(dest,'ready'),sourceHash);}
 const shell=await readFile(path.join(root,'game-shell.html'),'utf8'),html=shell.replace('__COMPOSITION__',JSON.stringify(c).replaceAll('<','\\u003c')).replace('__PLAYER__','/.runtime/'+sourceHash+(c.version===4?'/scene-player.mjs':c.version===3?'/pilot-player.mjs':'/player.mjs'));await writeFile(path.join(experiments,id,'index.html'),html,{flag:'wx'});await writeFile(path.join(experiments,id,'composition.json'),JSON.stringify(c,null,2),{flag:'wx'});return {sourceHash,artifactHash:hash(html)};
}
