import {random,object,validate} from './domains.mjs';
export const concepts=[
 {id:'connection',meaning:'Join separated places or dependencies',branches:[{id:'link',action:'activate',intent:'Establish a route'},{id:'relay',action:'carry',intent:'Connect places by transporting a physical core'}]},
 {id:'growth',meaning:'Expand through successive changes',branches:[{id:'extend',action:'activate',intent:'Extend the accessible structure'},{id:'nurture',action:'hold',intent:'Sustain contact to develop the structure'}]},
 {id:'migration',meaning:'Move something to a place where it can continue',branches:[{id:'relocate',action:'carry',intent:'Move a core to the receiving anchor'},{id:'settle',action:'hold',intent:'Occupy a new anchor before proceeding'}]},
 {id:'memory',meaning:'Past actions change what is possible next',branches:[{id:'record',action:'activate',intent:'Record an anchor as a prerequisite'},{id:'retain',action:'hold',intent:'Complete a sustained action that remains recorded'}]},
 {id:'exchange',meaning:'Transfer changes access or ownership',branches:[{id:'transfer',action:'carry',intent:'Transfer a core to open the next dependency'},{id:'authorize',action:'activate',intent:'Authorize an exchange between anchors'}]},
 {id:'patience',meaning:'Commit time before receiving a consequence',branches:[{id:'dwell',action:'hold',intent:'Remain at an anchor until its work completes'},{id:'journey',action:'carry',intent:'Commit to a return journey with a core'}]},
 {id:'order',meaning:'Relationships impose an order on actions',branches:[{id:'sequence',action:'activate',intent:'Activate prerequisites before dependent anchors'},{id:'process',action:'hold',intent:'Finish a process before its successor starts'}]},
 {id:'care',meaning:'Preserve and move vulnerable things',branches:[{id:'rescue',action:'carry',intent:'Recover a core to the receiving anchor'},{id:'restore',action:'hold',intent:'Restore an anchor through sustained presence'}]}
];
export function rollConcepts(seed,depth=2){if(!Number.isInteger(seed)||seed<0||seed>4294967295||![1,2,3].includes(depth))throw Error('Invalid seed or complexity');const rng=random(seed),pool=[...concepts];for(let i=pool.length-1;i;i--){const j=Math.floor(rng()*(i+1));[pool[i],pool[j]]=[pool[j],pool[i]];}return {seed,depth,concepts:pool.slice(0,3).map(c=>({id:c.id,meaning:c.meaning,branches:c.branches.slice(0,depth===1?1:2)}))};}
const layouts=['arc','switchback','crown','fork','terraces'];
function positions(layout,n){return Array.from({length:n},(_,i)=>{const t=i+1;switch(layout){case 'arc':return {x:Math.sin(t/(n+1)*Math.PI)*18-9,z:8-Math.cos(t/(n+1)*Math.PI)*17,y:0};case 'switchback':return {x:i%2?9:-9,z:2-i*7,y:0};case 'crown':return {x:Math.cos(t/n*Math.PI*2)*16,z:Math.sin(t/n*Math.PI*2)*16,y:0};case 'fork':return {x:(i%2?1:-1)*(7+Math.floor(i/2)*4),z:5-Math.floor(i/2)*10,y:0};default:return {x:(i%3-1)*11,z:4-Math.floor(i/3)*14,y:0};}});}
export function signature(c){return JSON.stringify({layout:c.layout,required:c.required,exit:c.exit,nodes:c.nodes.map(n=>({action:n.action,requires:n.requires,receiver:n.action==='carry'?n.receiver:null})),edges:c.edges.map(e=>[e.a,e.b,e.requires])});}
export function expand(rolled,used=new Set()){
 const rng=random(rolled.seed^0x123456),out=[];
 for(let attempt=0;attempt<160&&out.length<3;attempt++){
  const layout=layouts[Math.floor(rng()*layouts.length)],count=3+rolled.depth;const pos=positions(layout,count),nodes=[];
  for(let i=0;i<count;i++){const c=rolled.concepts[i%3],b=c.branches[Math.floor(rng()*c.branches.length)];const requires=i===0?[]:rolled.depth===1?[`n${i-1}`]:Array.from({length:i},(_,j)=>j).filter(()=>rng()<(rolled.depth===3?.45:.25)).map(j=>'n'+j);nodes.push({id:'n'+i,concept:c.id,branch:b.id,intent:b.intent,action:b.action,position:pos[i],requires,receiver:rng()<.5?'home':i?'n'+(i-1):'home',seconds:b.action==='hold'?2+rolled.depth:1});}
  // A deterministic spatial tree provides walkable routes; prerequisites gate interactions, not invisible movement.
  const edges=nodes.map((n,i)=>({a:i&&rng()<.65?'n'+Math.floor(rng()*i):'home',b:n.id,requires:n.requires.slice(0,1)}));
  const goal=['network','expedition','recovery'][Math.floor(rng()*3)];const required=new Set(goal==='network'?nodes.map(n=>n.id):nodes.slice(0,3).map(n=>n.id));if(goal==='recovery')nodes.filter(n=>n.action==='carry').forEach(n=>required.add(n.id));const exit=goal==='expedition'?nodes.at(-1).id:'home';if(exit!=='home')required.add(exit);let changed=true;while(changed){changed=false;for(const id of [...required]){const node=nodes.find(n=>n.id===id),edge=edges.find(e=>e.b===id);for(const dep of [...node.requires,...(edge.a==='home'?[]:[edge.a])])if(!required.has(dep)){required.add(dep);changed=true;}}}
  const c={version:2,seed:rolled.seed,depth:rolled.depth,layout,goal,required:[...required].sort(),exit,concepts:rolled.concepts.map(c=>c.id),home:{x:0,y:0,z:23},nodes,edges,duration:300,speed:8,defaults:['1 world unit = 1 metre','2.8 metre bridge width','fixed 300 second deadline','objective closure includes all rolled concepts'],palette:['lagoon','solar','violet','glacier','coral'][Math.floor(rng()*5)]};
  validateComposition(c);if(!used.has(signature(c))&&!out.some(x=>signature(x)===signature(c)))out.push(c);
 }
 if(!out.length)throw Error('No unused supported composition for this roll');return out;
}
export function validateComposition(c){
 if(c.version!==2||!layouts.includes(c.layout)||c.nodes.length<4||c.nodes.length>6||c.edges.length!==c.nodes.length||c.duration!==300||c.speed!==8)throw Error('Unsupported composition bounds');
 const ids=new Set(['home']);for(const n of c.nodes){if(ids.has(n.id)||!/^n[0-5]$/.test(n.id)||!['activate','hold','carry'].includes(n.action)||!c.concepts.includes(n.concept))throw Error('Invalid domain instance');if(!Object.values(n.position).every(Number.isFinite)||Math.abs(n.position.x)>40||Math.abs(n.position.z)>40||n.position.y!==0)throw Error('Invalid spatial bounds');if(!n.requires.every(x=>ids.has(x)&&x!=='home')||!ids.has(n.receiver))throw Error('Dependency cycle or reference');if(n.seconds<1||n.seconds>5)throw Error('Invalid interaction time');ids.add(n.id);}
 if(!c.concepts.every(x=>c.nodes.some(n=>n.concept===x)))throw Error('Concept was dropped');
 const reached=new Set(['home']);for(const e of c.edges){if(!reached.has(e.a)||!ids.has(e.b)||reached.has(e.b)||!e.requires.every(x=>ids.has(x)&&Number(x.slice(1))<Number(e.b.slice(1))))throw Error('Disconnected spatial tree');reached.add(e.b);}if(reached.size!==ids.size)throw Error('Unreachable anchor');if(!['network','expedition','recovery'].includes(c.goal)||!ids.has(c.exit)||!Array.isArray(c.required)||!c.required.length||!c.required.every(x=>ids.has(x)&&x!=='home')||!c.concepts.every(x=>c.nodes.some(n=>n.concept===x&&c.required.includes(n.id))))throw Error('Incomplete objective');return c;
}
export const interpretationSchema=n=>object({choice:{type:'integer',minimum:0,maximum:n-1},intent:{type:'string',minLength:8,maxLength:180}});
export const editorialSchema=object({title:{type:'string',minLength:3,maxLength:45},palette:{type:'string',enum:['lagoon','solar','violet','glacier','coral']},tagline:{type:'string',minLength:8,maxLength:120}});
export function instructions(c){return 'Complete anchors '+c.required.map(x=>Number(x.slice(1))+1).join(', ')+', then '+(c.exit==='home'?'return to the landing pad':'reach anchor '+(Number(c.exit.slice(1))+1))+'. '+[c.nodes.some(n=>n.action==='activate')?'E: activate a nearby unlocked beacon.':'',c.nodes.some(n=>n.action==='hold')?'Hold E near an unlocked ring to restore it.':'',c.nodes.some(n=>n.action==='carry')?'E: pick up a core; carry it to its marked receiver and press E.':''].filter(Boolean).join(' ')+' White links show prerequisites. WASD / arrows move. Finish before 300 seconds.';}
