import {flowWorld,flowNodes} from './kits/flow-layout.mjs';
import {readFileSync} from 'node:fs';
import {random} from './domains.mjs';
import {digest} from './factory.mjs';
import {transferWorld,validateWorld} from './kits/spatial-world.mjs';
import {trackFrame,trackGates,rallyVehicle} from './kits/track-layout.mjs';
import {pilotDomainGraph,compileDomainGraph} from './kits/domain-graph.mjs';
const options=JSON.parse(readFileSync(new URL('./pilot-options.json',import.meta.url),'utf8'));
import {rollConcepts} from './composition.mjs';
export const pilotKinds=['transfer','conduit','rally','checkpoint'];
// Automatic rolls avoid the overused transfer template; its components remain reusable.
export const automaticPilotKinds=['conduit','rally'];
export function pilotProfile(kind,seed){
 if(!Number.isInteger(seed)||seed<0||seed>4294967295)throw Error('Invalid pilot seed');
 if(!pilotKinds.includes(kind))throw Error('Unknown pilot capability family');const rolled=rollConcepts(seed,2);
 const x={version:3,kind,seed,depth:2,concepts:rolled.concepts.map(x=>x.id),conceptRoll:rolled,deadlineSeconds:300,title:kind,palette:'lagoon',goal:'',controls:'',playerStart:{x:0,y:0,z:0}};
 if(kind==='transfer')Object.assign(x,{goal:'Carry each energy cell into the matching numbered bay. One cell at a time.',controls:'WASD / arrows move · E pick up or deliver · Esc pause · R restart · F fullscreen',playerStart:{x:0,y:0,z:12},nodes:[{id:'c0',x:-10,z:-8,receiver:{x:10,z:9}},{id:'c1',x:10,z:-8,receiver:{x:-10,z:9}},{id:'c2',x:0,z:-10,receiver:{x:0,z:10}}],view:'overhead',world:'warehouse'});
 if(kind==='conduit'){
  const rng=random(seed^0x32af1),pick=xs=>structuredClone(xs[Math.floor(rng()*xs.length)]),flowLayout=pick(options.conduit.layouts),flowProcess=pick(options.conduit.processes);
  Object.assign(x,{goal:'Fill the blue tank before the waste tank fills. Open a route valve before starting the selector. The short route saves walking time but wastes more fluid; the long route leaves more room for mistakes. The selector cycles SHORT, LONG, BOTH, OFF; each route valve turns independently.',controls:'WASD / arrows move · E turn nearby valve · Esc pause · R restart · F fullscreen',playerStart:{x:0,y:0,z:12},nodes:flowNodes(flowLayout),flowLayout,flowProcess,spatialWorld:flowWorld(flowLayout),view:'first-person',world:'pump-room',selection:{catalogHash:digest(options),seed,layout:flowLayout.id,process:flowProcess.id,method:'seeded-compatible-list-selection'}});
 }
 if(kind==='rally'){
  const rng=random(seed^0x714ac),pick=xs=>xs[Math.floor(rng()*xs.length)],track={...pick(options.rally.tracks),width:pick(options.rally.widths)},handling={...pick(options.rally.handling)},presentation={...pick(options.rally.presentation)},shortcut={...pick(options.rally.shortcuts.filter(s=>s.allowedTracks.includes(track.id)))},start=trackFrame(track,0);
  Object.assign(x,{goal:'Clear every gate in order. Follow the wide road or take the narrow infield shortcut between its marked gates. The shortcut saves distance but requires precise steering. Brake before bends; hold brake to reverse if stuck. Beat your best lap.',controls:'W / ↑ accelerate · S / ↓ brake / reverse · A/D steer · Esc pause · R restart · F fullscreen',playerStart:{x:start.x,y:0,z:start.z},headingStart:start.heading,track,handling,presentation,shortcut,vehicle:{...rallyVehicle},nodes:trackGates(track,shortcut),view:'chase',world:'canyon-circuit',selection:{catalogHash:digest(options),seed,track:track.id,width:track.width,handling:handling.id,presentation:presentation.id,shortcut:shortcut.id,method:'seeded-compatible-list-selection'}});
 }
 if(kind==='checkpoint'){const rng=random(seed^0x2c71a),pick=xs=>xs[Math.floor(rng()*xs.length)],track={...pick(options.rally.tracks),width:pick(options.rally.widths)},handling={...pick(options.rally.handling)},presentation={...pick(options.rally.presentation)},shortcut={...pick(options.rally.shortcuts.filter(s=>s.allowedTracks.includes(track.id)))},start=trackFrame(track,0);Object.assign(x,{goal:'Reach every beacon in order before time runs out. Choose the safer outer line or the shorter inner line at each marked turn. Learn the route, then beat your best time.',controls:'W / ↑ accelerate · S / ↓ brake / reverse · A/D steer · Esc pause · R restart · F fullscreen',playerStart:{x:start.x,y:0,z:start.z},headingStart:start.heading,track,handling,presentation,shortcut,vehicle:{...rallyVehicle},nodes:trackGates(track,shortcut),view:'chase',world:'beacon-run',selection:{catalogHash:digest(options),seed,track:track.id,width:track.width,handling:handling.id,presentation:presentation.id,shortcut:shortcut.id,method:'seeded-compatible-list-selection'}});}
 if(kind==='transfer'){const rng=random(seed^0x51f15e),layout=structuredClone(options.transfer.layouts[Math.floor(rng()*options.transfer.layouts.length)]);x.transferLayout=layout;const cargoPool=options.transfer.cargoLayouts.filter(cargo=>layout.allowedCargo.includes(cargo.id));if(!cargoPool.length)throw Error('No compatible cargo layout');x.cargoLayout=structuredClone(cargoPool[Math.floor(rng()*cargoPool.length)]);x.nodes=structuredClone(x.cargoLayout.nodes);x.spatialWorld=transferWorld(layout);x.goal='Deliver all three cells to matching bays. Deliveries 1 and 2 open their numbered shortcut doors. Choose your delivery order and route.';x.selection={catalogHash:digest(options),seed,layout:layout.id,cargo:x.cargoLayout.id,method:'seeded-compatible-list-selection'};}
 x.replay={mechanism:'personal-best',reason:'Improve completion time under the same course and rules.',recordKey:digest({kind,nodes:x.nodes,spatialWorld:x.spatialWorld,track:x.track,handling:x.handling,shortcut:x.shortcut,vehicle:x.vehicle,deadlineSeconds:x.deadlineSeconds,fillSeconds:x.fillSeconds,flowProcess:x.flowProcess})};
 if(kind==='rally')x.replay.reason='Master the narrow shortcut to save time, or use the wider bend for more steering room.';
 if(kind==='checkpoint')x.replay.reason='Learn the beacon order, choose cleaner lines, and beat your best completion time.';
 if(kind==='checkpoint')x.replay.reason='Learn the beacon order, choose cleaner lines, and beat your best completion time.';
 if(kind==='transfer')x.replay.reason='Try a different delivery order and use the doors it opens to reduce travel time.';
 if(kind==='conduit')x.replay.reason='Try the faster setup to beat your time, or use the longer route to leave more waste capacity for mistakes.';
 x.domainGraph=pilotDomainGraph(x);return validatePilot(x);
}
export function validatePilot(c){if(c.kind==='transfer'){if(!c.transferLayout?.allowedCargo?.includes(c.cargoLayout?.id))throw Error('Incompatible cargo and shortcut layout');if(!options.transfer.cargoLayouts.some(l=>digest(l)===digest(c.cargoLayout))||digest(c.nodes)!==digest(c.cargoLayout.nodes))throw Error('Invalid cargo layout');if(!options.transfer.layouts.some(l=>digest(l)===digest(c.transferLayout))||digest(c.spatialWorld)!==digest(transferWorld(c.transferLayout)))throw Error('Invalid seeded world');validateWorld(c.spatialWorld,c.domainGraph);}compileDomainGraph(c.domainGraph);if(digest(c.domainGraph)!==digest(pilotDomainGraph(c)))throw Error('Pilot domain graph differs from seeded profile');if(c.version!==3||!pilotKinds.includes(c.kind)||c.deadlineSeconds!==300||!['lagoon','solar','violet','glacier','coral'].includes(c.palette))throw Error('Unsupported pilot profile');const ids=new Set();for(const n of c.nodes){if(ids.has(n.id)||!Number.isFinite(n.x)||!Number.isFinite(n.z)||Math.abs(n.x)>30||Math.abs(n.z)>30)throw Error('Invalid pilot instance');ids.add(n.id);}if(c.kind==='transfer'&&(c.nodes.length!==3||c.nodes.some(n=>!n.receiver||!Number.isFinite(n.receiver.x)||!Number.isFinite(n.receiver.z))))throw Error('Invalid delivery contract');if(c.kind==='conduit'){if(!options.conduit.layouts.some(l=>digest(l)===digest(c.flowLayout))||!options.conduit.processes.some(p=>digest(p)===digest(c.flowProcess))||digest(c.nodes)!==digest(flowNodes(c.flowLayout))||digest(c.spatialWorld)!==digest(flowWorld(c.flowLayout)))throw Error('Invalid seeded flow contract');validateWorld(c.spatialWorld,c.domainGraph);}if(c.kind==='rally'){if(digest(c.nodes)!==digest(trackGates(c.track,c.shortcut))||digest(c.vehicle)!==digest(rallyVehicle)||!options.rally.shortcuts.some(s=>digest(s)===digest(c.shortcut)&&s.allowedTracks.includes(c.track.id))||!options.rally.presentation.some(p=>Object.entries(p).every(([k,v])=>c.presentation?.[k]===v))||!options.rally.widths.includes(c.track?.width)||!options.rally.tracks.some(t=>Object.entries(t).every(([k,v])=>c.track[k]===v))||!options.rally.handling.some(h=>Object.entries(h).every(([k,v])=>c.handling?.[k]===v)))throw Error('Invalid seeded track contract');for(const [i,n] of c.nodes.entries()){const expected=trackFrame(c.track,c.nodes[i].t);if(Math.hypot(n.x-expected.x,n.z-expected.z)>.00001)throw Error('Checkpoint off track');}}return c;}
