import {solidOpen} from './kits/spatial-world.mjs';
import * as THREE from './vendor/three/three.module.js';
import {trackSegments} from './kits/track-layout.mjs';
import {createPilotEngine} from './kits/pilot-kit.mjs';
const $=id=>document.getElementById(id),c=JSON.parse($('composition').textContent);
const recordKey=c.replay?'nexus-best:'+new URL(import.meta.url).pathname.split('/').slice(0,3).join('/')+':'+c.replay.recordKey:null;
function readRecord(){try{const n=Number(localStorage.getItem(recordKey));return recordKey&&Number.isFinite(n)&&n>0&&n<=c.deadlineSeconds?n:null;}catch{return null;}}
let persistedBest=readRecord();const game=createPilotEngine(c,{bestSeconds:persistedBest}).n.arcade,keys=new Set();let manual=false,last=performance.now(),acc=0,mode='',previousEvents=0,audio;
const renderer=new THREE.WebGLRenderer({canvas:$('view'),antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(c.kind==='conduit'?65:48,1,.1,300);
const palettes={courier:[0x17272d,0x99ffd0,0xffab5e],conduit:[0x130f23,0x4ad9ff,0xffb544],rally:[c.presentation?.sky??0xaed8db,0x39dfff,c.presentation?.accent??0xf57243]},[bg,primary,baseAccent]=palettes[c.kind],accent=c.kind==='rally'?(c.presentation?.accent??baseAccent):({lagoon:0xf5b06b,solar:0xffca61,violet:0xb99aff,glacier:0x9cecff,coral:0xff8d93}[c.palette]??baseAccent);scene.background=new THREE.Color(bg);scene.fog=new THREE.Fog(bg,60,150);
scene.add(new THREE.HemisphereLight(c.kind==='rally'?0xffffff:0xbacbd8,0x352b34,c.kind==='conduit'?1:2.5));const sun=new THREE.DirectionalLight(0xffe9d1,c.kind==='conduit'?1:3);sun.position.set(-18,35,15);sun.castShadow=true;sun.shadow.bias=-.0002;sun.shadow.normalBias=.06;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-40,right:40,top:40,bottom:-40});scene.add(sun);
const material=(color,metalness=.2,roughness=.6)=>new THREE.MeshStandardMaterial({color,metalness,roughness});
const glow=color=>{const m=material(color,.4,.25);m.emissive=new THREE.Color(color);m.emissiveIntensity=.65;return m;};
const floor=material(c.kind==='courier'?0x657b78:c.kind==='conduit'?0x222d42:0x565b57),wall=material(c.kind==='courier'?0xd2dfc0:c.kind==='conduit'?0x343446:0xb88d5e),lit=glow(primary),hot=glow(accent);
function mesh(geo,mat,x,y,z){const m=new THREE.Mesh(geo,mat);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;scene.add(m);return m;}
function box(w,h,d,x,y,z,mat=wall){return mesh(new THREE.BoxGeometry(w,h,d),mat,x,y,z);}
const actors=new Map(),targets=new Map(),rings=[];
function numberPlate(text,x,y,z){const canvas=document.createElement('canvas');canvas.width=128;canvas.height=128;const ctx=canvas.getContext('2d');ctx.fillStyle='#10232d';ctx.fillRect(0,0,128,128);ctx.fillStyle='#ffffff';ctx.font='bold '+(text.length>1?43:88)+'px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,64,67);const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;const sprite=new THREE.Sprite(new THREE.SpriteMaterial({map:texture,depthTest:false}));sprite.position.set(x,y,z);sprite.scale.set(2.1,2.1,1);scene.add(sprite);return sprite;}
const cellLabels=new Map(),doors=[];let tank;
if(c.kind==='courier'){
 box(30,.8,30,0,-.45,0,floor);for(const x of [-14.5,14.5])box(.6,2,30,x,.8,0);for(const z of [-14.5,14.5])box(30,2,.6,0,.8,z);
 for(const solid of c.spatialWorld.solids){const block=box(solid.width,solid.height,solid.depth,solid.x,solid.height/2,solid.z,solid.openWhen?hot:wall);if(solid.openWhen){const label=numberPlate(String(solid.label),solid.x,solid.height+.7,solid.z);label.scale.set(1.2,1.2,1);doors.push({solid,block,label});for(const side of [-1,1])box(solid.width,.035,.1,solid.x,.03,solid.z+side*solid.depth/2,lit);}else for(const y of [.7,1.4,2.1])box(solid.width+.02,.1,solid.depth-.15,solid.x,y,solid.z,floor);}
 for(let i=0;i<13;i++)box(.045,.02,28,-12+i*2,.005,0,material(0x90a89d));
 c.nodes.forEach((n,i)=>{const col=[0xffcb69,0x76d7ff,0xff91bf][i],mat=glow(col);const cell=mesh(new THREE.IcosahedronGeometry(.65,1),mat,n.x,.8,n.z);const ring=new THREE.Mesh(new THREE.TorusGeometry(.82,.065,8,32),hot);ring.rotation.x=Math.PI/2;cell.add(ring);actors.set(n.id,cell);const cellLabel=numberPlate(String(i+1),n.x,2,n.z);cellLabel.scale.set(1.4,1.4,1);cellLabels.set(n.id,cellLabel);const outer=Math.abs(n.receiver.x)>7,bayLabel=numberPlate(String(i+1),n.receiver.x+(outer?Math.sign(n.receiver.x)*2.2:0),.7,n.receiver.z+(outer?0:1.9));bayLabel.scale.set(1.5,1.5,1);const base=box(3,.15,3,n.receiver.x,.1,n.receiver.z,mat);targets.set(n.id,base);for(const side of [-1,1])box(.2,1.1,3,n.receiver.x+side*1.5,.55,n.receiver.z,floor);});
}else if(c.kind==='conduit'){
 box(30,.7,30,0,-.4,0,floor);box(30,7,.7,0,3.4,-14,wall);for(const x of [-14.5,14.5])box(.7,7,30,x,3.4,0,wall);
 for(const n of c.nodes){box(2.8,1.2,2.8,n.x,.6,n.z,wall);const valve=mesh(new THREE.TorusGeometry(.85,.14,12,32),hot,n.x,1.5,n.z);valve.rotation.x=-Math.PI/2;actors.set(n.id,valve);const arrow=box(.13,.13,1.35,n.x,1.72,n.z,hot);targets.set(n.id,arrow);const target=box(.16,.1,2.2,n.x,.08,n.z,lit);target.rotation.y=n.target*Math.PI/2;const mark=mesh(new THREE.ConeGeometry(.38,.7,3),lit,n.x+Math.sin(n.target*Math.PI/2)*1.5,.15,n.z+Math.cos(n.target*Math.PI/2)*1.5);mark.rotation.x=Math.PI/2;mark.rotation.z=-n.target*Math.PI/2;}
 for(let i=0;i<2;i++){const a=c.nodes[i],b=c.nodes[i+1];box(b.x-a.x,.25,.25,(a.x+b.x)/2,1.2,0,lit);}
 box(3,5,2,0,2.5,-8,wall);tank=box(2.4,.1,.25,0,.2,-6.9,lit);box(8,.15,.15,0,5.5,-12,hot);
 for(const x of [-8,8]){const light=new THREE.PointLight(primary,55,18,2);light.position.set(x,3,0);scene.add(light);}
}else{
 box(160,1,160,0,-1,0,material(c.presentation?.ground??0xd3ac70));
 const points=trackSegments(c.track),vertices=[],indices=[];
 for(const p of points){for(const side of [-1,1])vertices.push(p.x+p.nx*c.track.width/2*side,0,p.z+p.nz*c.track.width/2*side);}
 for(let i=0;i<points.length-1;i++){const a=i*2;indices.push(a,a+2,a+1,a+1,a+2,a+3);}
 const road=new THREE.BufferGeometry();road.setAttribute('position',new THREE.Float32BufferAttribute(vertices,3));road.setIndex(indices);road.computeVertexNormals();const roadMat=floor.clone();roadMat.side=THREE.DoubleSide;mesh(road,roadMat,0,0,0);
 for(let i=0;i<points.length-1;i+=4){const p=points[i],mark=box(.18,.025,.8,p.x,.02,p.z,material(0xe8e3ce));mark.rotation.y=p.heading;for(const side of [-1,1]){const curb=box(.22,.18,.85,p.x+p.nx*c.track.width/2*side,.08,p.z+p.nz*c.track.width/2*side,hot);curb.rotation.y=p.heading;}}
 c.nodes.forEach((n,i)=>{const ring=new THREE.Group();ring.position.set(n.x,0,n.z);ring.rotation.y=n.heading;scene.add(ring);for(const x of [-c.track.width/2,c.track.width/2]){const p=new THREE.Mesh(new THREE.BoxGeometry(.35,5.5,.35),i===0?lit:hot);p.position.set(x,2.75,0);ring.add(p);}const top=new THREE.Mesh(new THREE.BoxGeometry(c.track.width+.4,.4,.4),lit);top.position.y=5.5;ring.add(top);const label=numberPlate(String(i+1),0,4.55,0);label.scale.set(1.2,1.2,1);ring.add(label);rings.push(ring);});
 for(let i=0;i<24;i++){const a=i*2.399,r=30+i%5*4;const rock=mesh(new THREE.DodecahedronGeometry(1,0),material(c.presentation?.rock??0xb88d5e,.05,.95),Math.cos(a)*r,2,Math.sin(a)*r);rock.scale.set(3+i%3,4+i%7,3+i%4);rock.rotation.y=a;const cap=mesh(new THREE.DodecahedronGeometry(1,0),material(c.presentation?.rock??0xb88d5e,.05,.9),Math.cos(a)*r+.8,4+i%4,Math.sin(a)*r);cap.scale.set(2+i%2,2.5+i%3,2+i%2);cap.rotation.y=-a;}
}
const actor=new THREE.Group();scene.add(actor);if(c.kind==='rally'){const body=new THREE.Mesh(new THREE.BoxGeometry(1.4,.6,2.3),material(accent,.45,.28));body.position.y=.55;actor.add(body);const roof=new THREE.Mesh(new THREE.BoxGeometry(1,.5,1),material(0x142834,.5,.2));roof.position.set(0,1,-.25);actor.add(roof);for(const z of [-.92,.72]){const glass=new THREE.Mesh(new THREE.BoxGeometry(.94,.34,.06),material(0x75bddd,.65,.18));glass.position.set(0,.88,z);glass.rotation.x=z>0?-.25:.25;actor.add(glass);}for(const x of [-.47,.47]){const lamp=new THREE.Mesh(new THREE.BoxGeometry(.32,.13,.05),glow(0xff3939));lamp.position.set(x,.56,-1.17);actor.add(lamp);const head=new THREE.Mesh(new THREE.BoxGeometry(.32,.14,.05),glow(0xffffdd));head.position.set(x,.55,1.17);actor.add(head);}const stripe=new THREE.Mesh(new THREE.BoxGeometry(.2,.025,.95),material(0xf3f7ef));stripe.position.set(0,.865,.68);actor.add(stripe);const spoiler=new THREE.Mesh(new THREE.BoxGeometry(1.5,.09,.3),material(0x13252c));spoiler.position.set(0,.92,-1.0);actor.add(spoiler);for(const x of [-.8,.8])for(const z of [-.75,.75]){const tire=new THREE.Mesh(new THREE.CylinderGeometry(.35,.35,.3,12),material(0x182129));tire.rotation.z=Math.PI/2;tire.position.set(x,.35,z);actor.add(tire);}}else{const body=new THREE.Mesh(new THREE.CapsuleGeometry(.4,.7,4,12),lit);body.position.y=.8;actor.add(body);}actor.visible=c.kind!=='conduit';const you=c.kind==='courier'?numberPlate('YOU',0,3.6,0):null;if(you)you.scale.set(1.2,.65,1);
function notify(state,message){if(parent!==window)parent.postMessage({type:'nexus-player',state,message},location.origin);}
function draw(){const s=game.snapshot();for(const {solid,block,label} of doors){const opened=solidOpen(solid,s.domainState);block.scale.y=opened?.03:1;block.position.y=opened?.035:solid.height/2;label.position.y=opened?.25:solid.height+.7;label.material.color.setHex(opened?primary:0xffffff);}if(recordKey&&s.mode==='won'&&s.bestSeconds!==persistedBest){try{localStorage.setItem(recordKey,String(s.bestSeconds));persistedBest=s.bestSeconds;}catch{}}if(mode!==s.mode){mode=s.mode;notify(mode);}actor.position.set(s.player.x,0,s.player.z);actor.rotation.y=s.heading;if(you)you.position.set(s.player.x,3.6,s.player.z);
 if(c.kind==='courier'){camera.position.set(s.player.x*.25,33,s.player.z*.25+25);camera.lookAt(s.player.x*.25,0,s.player.z*.25-2);for(const n of c.nodes){const m=actors.get(n.id);m.visible=!s.completed.includes(n.id);m.position.set(s.carry===n.id?s.player.x:n.x,s.carry===n.id?1.9:.65,s.carry===n.id?s.player.z:n.z);m.rotation.y=s.elapsed;const label=cellLabels.get(n.id);label.visible=m.visible;label.position.set(m.position.x,m.position.y+1.2,m.position.z);targets.get(n.id).material.emissiveIntensity=s.completed.includes(n.id)?.08:.65;}}
 if(c.kind==='conduit'){camera.position.set(s.player.x,2.6,s.player.z+1);camera.lookAt(s.player.x,1.1,s.player.z-9);for(let i=0;i<c.nodes.length;i++){targets.get(c.nodes[i].id).rotation.y=s.rotation[i]*Math.PI/2;actors.get(c.nodes[i].id).material=s.rotation[i]===c.nodes[i].target?lit:hot;}tank.scale.y=Math.max(.1,s.fill*42);tank.position.y=.2+s.fill*2.1;}
 if(c.kind==='rally'){camera.position.set(s.player.x-Math.sin(s.heading)*9,6,s.player.z-Math.cos(s.heading)*9);camera.lookAt(s.player.x+Math.sin(s.heading)*5,1,s.player.z+Math.cos(s.heading)*5);rings.forEach((r,i)=>{r.visible=i>=s.completed.length&&i<s.completed.length+3;r.children.slice(0,3).forEach(m=>m.material=i===s.completed.length?lit:hot);r.scale.setScalar(i===s.completed.length?1.06:1);});}
 $('title').textContent=c.title;$('counter-label').textContent=c.kind==='courier'?'DELIVERIES ':c.kind==='conduit'?'RESERVOIR ':'CHECKPOINTS ';$('time').textContent=Math.ceil(c.deadlineSeconds-s.elapsed);$('progress').textContent=c.kind==='conduit'?Math.round(s.fill*100)+'%':s.completed.length+' / '+c.nodes.length;$('hint').textContent=c.kind==='courier'?(s.carry?'Cell '+(c.nodes.findIndex(n=>n.id===s.carry)+1)+' → matching bay · E to deliver':'E pick up · match numbered bays · deliveries 1/2 open shortcuts'):c.kind==='conduit'?'E turns a nearby valve 90° · align amber bars with blue arrows':Math.round(s.speed*3.6)+' km/h · checkpoint '+Math.min(s.completed.length+1,c.nodes.length)+' / '+c.nodes.length;
 if(s.mode==='play'&&doors.length)$('hint').textContent+=' · Doors '+doors.filter(d=>solidOpen(d.solid,s.domainState)).length+' / '+doors.length;
 if(s.mode==='play'&&c.replay)$('hint').textContent+=' · Time '+s.elapsed.toFixed(1)+'s · Best '+(s.bestSeconds===null?'—':s.bestSeconds.toFixed(2)+'s');
 $('overlay').hidden=s.mode==='play';$('overlay-title').textContent=s.mode==='title'?c.title:s.mode==='pause'?'Paused':s.mode==='won'?'Complete!':'Time expired';$('instructions').textContent=s.mode==='won'?('Time '+s.lastResult.seconds.toFixed(2)+'s · Best '+s.bestSeconds.toFixed(2)+'s. '+(s.lastResult.previousBest===null?'First record set.':s.lastResult.personalBest?'Improved by '+s.lastResult.improvement.toFixed(2)+'s!':'Try a different braking point or route to improve.')+' '+c.replay.reason):c.goal;$('start').textContent=s.mode==='pause'?'RESUME':s.mode==='title'?'PLAY':'PLAY AGAIN';$('pause').textContent=s.mode==='pause'?'Resume':'Pause';document.querySelector('#instructions+p').textContent=c.controls;
 const newest=s.events.at(-1);if(newest&&JSON.stringify(newest)!==previousEvents&&['delivered','turned','checkpoint','won'].includes(newest.type)&&$('sound').checked){audio??=new AudioContext();const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);o.frequency.value=350+s.completed.length*90;g.gain.setValueAtTime(.04,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.15);o.start();o.stop(audio.currentTime+.15);}previousEvents=JSON.stringify(newest);renderer.render(scene,camera);
}
function advance(ms){if(!Number.isFinite(ms)||ms<0||ms>420000)throw Error('Invalid simulation interval');acc+=ms/1000;while(acc>=.05){game.step(.05,{x:Number(keys.has('KeyD')||keys.has('ArrowRight'))-Number(keys.has('KeyA')||keys.has('ArrowLeft')),z:Number(keys.has('KeyS')||keys.has('ArrowDown'))-Number(keys.has('KeyW')||keys.has('ArrowUp')),interact:keys.has('KeyE')||keys.has('Space')});acc-=.05;}draw();}
function resume(){keys.clear();acc=0;audio?.resume();if(game.snapshot().mode==='pause')game.pause();else{game.reset();game.start();}draw();}function pause(){keys.clear();game.pause();draw();}
$('start').onclick=resume;$('pause').onclick=pause;addEventListener('keydown',e=>{if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(e.repeat)return;keys.add(e.code);if(e.code==='KeyF'){if(document.fullscreenElement)document.exitFullscreen?.();else document.documentElement.requestFullscreen?.();}if(e.code==='Escape')pause();if(e.code==='KeyR'){game.reset();game.start();acc=0;}draw();});addEventListener('keyup',e=>keys.delete(e.code));function suspend(){keys.clear();acc=0;if(game.snapshot().mode==='play')game.pause();audio?.suspend();draw();}addEventListener('blur',suspend);addEventListener('visibilitychange',()=>{if(document.hidden)suspend();});
function resize(){renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();draw();}addEventListener('resize',resize);
window.render_game_to_text=()=>JSON.stringify(game.snapshot());window.advanceTime=ms=>{manual=true;advance(ms);};window.__renderEvidence=()=>({three:THREE.REVISION,triangles:renderer.info.render.triangles,drawCalls:renderer.info.render.calls});resize();notify('ready');function frame(now){if(!manual&&!document.hidden&&game.snapshot().mode==='play')advance(Math.min(250,now-last));last=now;requestAnimationFrame(frame);}requestAnimationFrame(frame);
