import {rollConcepts} from './composition.mjs';
export const pilotKinds=['courier','conduit','rally'];
export function pilotProfile(kind,seed){
 if(!pilotKinds.includes(kind))throw Error('Unknown pilot capability family');const rolled=rollConcepts(seed,2);
 const x={version:3,kind,seed,depth:2,concepts:rolled.concepts.map(x=>x.id),conceptRoll:rolled,deadlineSeconds:300,title:kind,palette:'lagoon',goal:'',controls:'',playerStart:{x:0,y:0,z:0}};
 if(kind==='courier')Object.assign(x,{goal:'Carry each energy cell into the matching numbered bay. One cell at a time.',controls:'WASD / arrows move · E pick up or deliver · Esc pause · R restart',playerStart:{x:0,y:0,z:12},nodes:[{id:'c0',x:-10,z:-8,receiver:{x:10,z:9}},{id:'c1',x:10,z:-8,receiver:{x:-10,z:9}},{id:'c2',x:0,z:-10,receiver:{x:0,z:10}}],view:'overhead',world:'warehouse'});
 if(kind==='conduit')Object.assign(x,{goal:'Turn all three valves toward the blue outlet arrows. Connected flow fills the reservoir.',controls:'WASD / arrows move · E turn nearby valve · Esc pause · R restart',playerStart:{x:0,y:0,z:12},nodes:[{id:'v0',x:-6,z:0,target:0,rotation:1},{id:'v1',x:0,z:0,target:1,rotation:3},{id:'v2',x:6,z:0,target:3,rotation:0}],fillSeconds:8,view:'first-person',world:'pump-room'});
 if(kind==='rally')Object.assign(x,{goal:'Drive through every checkpoint in order, then cross the finish line. Brake before tight turns.',controls:'W / ↑ accelerate · S / ↓ brake · A/D steer · Esc pause · R restart',playerStart:{x:18,y:0,z:0},nodes:Array.from({length:8},(_,i)=>({id:'g'+i,x:Math.cos((i+1)/8*Math.PI*2)*18,z:Math.sin((i+1)/8*Math.PI*2)*18})),view:'chase',world:'canyon-circuit'});
 return validatePilot(x);
}
export function validatePilot(c){if(c.version!==3||!pilotKinds.includes(c.kind)||c.deadlineSeconds!==300||!['lagoon','solar','violet','glacier','coral'].includes(c.palette))throw Error('Unsupported pilot profile');const ids=new Set();for(const n of c.nodes){if(ids.has(n.id)||!Number.isFinite(n.x)||!Number.isFinite(n.z)||Math.abs(n.x)>30||Math.abs(n.z)>30)throw Error('Invalid pilot instance');ids.add(n.id);}if(c.kind==='courier'&&(c.nodes.length!==3||c.nodes.some(n=>!n.receiver||!Number.isFinite(n.receiver.x)||!Number.isFinite(n.receiver.z))))throw Error('Invalid delivery contract');if(c.kind==='conduit'&&(c.nodes.length!==3||c.fillSeconds!==8||c.nodes.some(n=>![0,1,2,3].includes(n.target)||![0,1,2,3].includes(n.rotation))))throw Error('Invalid flow contract');if(c.kind==='rally'&&c.nodes.length!==8)throw Error('Invalid checkpoint contract');return c;}
