import {mkdir,writeFile,readFile} from 'node:fs/promises';
import path from 'node:path';
import {pilotProfile,validatePilot} from './pilot-spec.mjs';
import {Models} from './model.mjs';
import {editorialSchema,interpretationSchema} from './composition.mjs';
import {reviewSchema} from './domains.mjs';
import {atomicJSON,writerLease,deadline,contracts,digest} from './factory.mjs';
import {experiments,build,fingerprint} from './assembly.mjs';
import {reviewPilot} from './pilot-review.mjs';
import {indexPreview} from './library.mjs';
export async function generatePilot({id,kind,seed,retryOf,signal,onProgress=()=>{}}){
 if(!/^[a-zA-Z0-9][a-zA-Z0-9_-]{0,70}$/.test(id))throw Error('Invalid pilot ID');const profile=pilotProfile(kind,seed),admittedAt=Date.now(),release=await writerLease(id);let s;
 try{await mkdir(path.join(experiments,id));let prior;if(retryOf){if(!/^[a-zA-Z0-9][a-zA-Z0-9_-]{0,70}$/.test(retryOf))throw Error('Invalid prior attempt');prior=JSON.parse(await readFile(path.join(experiments,retryOf,'spine.json')));if(prior.seed!==seed||prior.composition.kind!==kind||!['FAIL','NEEDS_REVIEW'].includes(prior.status))throw Error('Incompatible retry');}const started=prior?.started??admittedAt,spec=await contracts();if(prior&&(prior.ruleVersion!==spec.hash||prior.deadline!==prior.started+1500000))throw Error('Retry changed frozen rules or original deadline');s={version:3,purpose:'foundation-pilot',id,ideaId:prior?.ideaId??retryOf??id,retryOf:retryOf??null,revisionCreated:Date.now(),started,deadline:started+1500000,seed,composition:profile,calls:[],status:'PLANNING',ruleVersion:spec.hash};const guard=deadline(s,signal),combined=AbortSignal.any([AbortSignal.timeout(guard.remaining()),...(signal?[signal]:[])]),save=async()=>{guard.check();await atomicJSON(path.join(experiments,id,'spine.json'),s);onProgress({id,status:s.status,elapsedMs:Date.now()-started});};await save();const models=new Models(s,save,{signal:combined});await models.check();
 s.plan=await models.askValidated('planner','pilot-plan','Explain one player intention using only the supplied implemented pilot behavior. Treat the independent rolled concepts as possibilities; explicitly avoid claiming they are proven gameplay contributions. Do not invent features. '+JSON.stringify({profile:{kind:profile.kind,goal:profile.goal,concepts:profile.conceptRoll,selection:profile.selection,replay:profile.replay.reason},choice:0}),interpretationSchema(1),500);
 s.status='WRITING';s.editorial=await models.askValidated('writer','pilot-write','Give this game a short title describing its spatial action or consequence, and an accurate description. Avoid player job titles. Avoid the words 3D, pilot, prototype, and demo in its title. '+JSON.stringify({kind,goal:profile.goal,intent:s.plan.intent}),editorialSchema,350);profile.title=s.editorial.title;profile.palette=s.editorial.palette;validatePilot(profile);s.status='ASSEMBLING';await save();Object.assign(s,await build(profile,id));s.status='TESTING';await save();s.browser=await reviewPilot(experiments,id,{signal:combined});const image=s.browser.image,detail=s.browser.detailImage,before=s.browser.initialImage;delete s.browser.image;delete s.browser.detailImage;delete s.browser.initialImage;if(before)await writeFile(path.join(experiments,id,'initial.png'),before,{flag:'wx'});if(detail)await writeFile(path.join(experiments,id,'detail.png'),detail,{flag:'wx'});if(image)await writeFile(path.join(experiments,id,'review.png'),image,{flag:'wx'});guard.check();if(s.browser.status!=='PASS')throw Error(s.browser.errors.join('; '));s.status='VISUAL_REVIEW';await save();s.visualFrames=[];for(const [frameId,bytes] of [...(before?[['initial',before]]:[]),['consequence',image],...(detail?[['detail',detail]]:[])]){const result=await models.askValidated('writer','pilot-review','Inspect this single actual gameplay image. Check visible geometry and readability of the controls and goal-related objects. In first-person views the player body need not be visible. For a detail crop judge only what is shown. Do not infer gameplay, novelty or audio. '+JSON.stringify({kind,frameId,goal:profile.goal,...(kind==='rally'?{sceneFacts:'Both roads are valid. The shortcut is optional. Curbs mark road edges and stop at joins; they are not goals. The initial frame shows a stationary car. Judge visible readability, not whether the player has chosen the correct route.'}:{})}),reviewSchema,500,bytes);s.visualFrames.push({frameId,imageHash:digest(bytes),result});await save();if(result.verdict!=='PASS')throw Error('Visual review '+frameId+': '+result.observation);}s.visual={verdict:'PASS',observation:s.visualFrames.map(f=>f.frameId+': '+f.result.observation).join('; ')};guard.check();if(s.sourceHash!==await fingerprint())throw Error('Source changed during pilot');s.signature=digest({kind,nodes:profile.nodes,world:profile.world,view:profile.view,domainGraph:profile.domainGraph,spatialWorld:profile.spatialWorld,track:profile.track,handling:profile.handling});s.previewVerdict='PASS';s.acceptance={verdict:'NEEDS_REVIEW',ruleVersion:s.ruleVersion,missing:['independent concept contribution','comparative novelty rubric','target-device performance','human comprehension']};s.status='NEEDS_REVIEW';s.elapsedMs=Date.now()-started;s.completed=Date.now();await save();await indexPreview(id);return s;
 }catch(e){if(!s)throw e;s.status=signal?.aborted?'CANCELLED':'FAIL';s.error=e.message;s.elapsedMs=Date.now()-s.started;await atomicJSON(path.join(experiments,id,'spine.json'),s);onProgress({id,status:s.status,error:s.error});return s;}finally{await release();}
}
