import {chromium} from 'playwright';
import {serveFiles} from './review3d.mjs';
import {digest} from './factory.mjs';
export async function reviewPilot(root,id,{signal}={}){
 const server=await serveFiles(root),report={status:'FAIL',method:'Keyboard-controlled accelerated Chromium software-WebGL pilot playthrough',checks:[],errors:[]};let browser;const check=(name,pass,observed)=>{report.checks.push({name,pass,observed});if(!pass)throw Error(name);};
 try{browser=await chromium.launch({headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});signal?.throwIfAborted();const abort=()=>browser.close().catch(()=>{});signal?.addEventListener('abort',abort,{once:true});const p=await browser.newPage({viewport:{width:1100,height:780}});p.setDefaultTimeout(15000);p.on('pageerror',e=>report.errors.push(e.message));const origin='http://127.0.0.1:'+server.address().port;await p.route('**/*',r=>r.request().url().startsWith(origin+'/')?r.continue():r.abort());await p.goto(origin+'/'+id+'/index.html');await p.waitForFunction(()=>!!window.render_game_to_text);const state=()=>p.evaluate(()=>JSON.parse(render_game_to_text())),tick=ms=>p.evaluate(ms=>advanceTime(ms),ms);const input=async(keys,ms=100)=>{signal?.throwIfAborted();for(const k of keys)await p.keyboard.down(k);await tick(ms);for(const k of keys)await p.keyboard.up(k);};await tick(0);check('title', (await state()).mode==='title');await p.click('#start');await tick(0);
 await p.keyboard.press('Escape');const paused=await state();await tick(180000);check('pause remains until explicit resume',(await state()).mode==='pause'&&(await state()).elapsed===paused.elapsed);await p.click('#start');await tick(0);check('explicit resume',(await state()).mode==='play');await p.evaluate(()=>dispatchEvent(new Event('blur')));await tick(1000);check('focus loss pauses',(await state()).mode==='pause');await p.click('#start');await tick(0);
 report.initialRender=await p.evaluate(()=>__renderEvidence());check('Three.js gameplay geometry',report.initialRender.triangles>1000);const start=await state();
 const go=async(x,z)=>{for(let i=0;i<350;i++){const s=await state(),dx=x-s.player.x,dz=z-s.player.z;if(Math.hypot(dx,dz)<.5)return;if(s.mode!=='play')throw Error('Premature '+s.mode);await input([Math.abs(dx)>.25?(dx>0?'KeyD':'KeyA'):null,Math.abs(dz)>.25?(dz>0?'KeyS':'KeyW'):null].filter(Boolean),100);}throw Error('Walking route stalled');};
 const playLoop=async(conservative=false)=>{
 if(start.kind==='courier'){
  await input(['KeyE']);check('empty space cannot pick up',(await state()).carry===null);
  for(const n of start.nodes){await go(n.x,12);await go(n.x,n.z);await input(['KeyE']);check('single cargo ownership '+n.id,(await state()).carry===n.id);await input(['KeyE']);check('wrong receiver cannot complete '+n.id,!(await state()).completed.includes(n.id));await go(n.x,12);await go(n.receiver.x,12);await go(n.receiver.x,n.receiver.z);await input(['KeyE']);check('matched receiver '+n.id,(await state()).completed.includes(n.id));if(!report.image){report.image=await p.screenshot();report.frame=await state();report.detailImage=await p.screenshot({clip:{x:120,y:440,width:860,height:280}});}}
 }else if(start.kind==='conduit'){
  await tick(5000);check('unconnected system cannot fill',(await state()).fill===0);
  for(let i=0;i<start.nodes.length;i++){const n=start.nodes[i];await go(n.x,4);await go(n.x,1);while((await state()).rotation[i]!==n.target){await input(['KeyE']);await tick(50);}await go(n.x,4);}
  await tick(2000);check('connected system accumulates',(await state()).fill>0);report.image=await p.screenshot();report.frame=await state();
  // Break a connection after progress; stored fill must decrease, not keep winning.
  await go(0,1);await input(['KeyE']);const fill=(await state()).fill;await tick(500);check('broken flow drains',(await state()).fill<fill);while((await state()).rotation[1]!==start.nodes[1].target){await input(['KeyE']);await tick(50);}await tick(8500);
 }else{
  await input(['KeyA'],100);check('steering stationary cannot earn checkpoint',(await state()).completed.length===0);
  for(let i=0;i<2200;i++){const s=await state();if(s.mode!=='play')break;const n=s.nodes[s.completed.length],desired=Math.atan2(n.x-s.player.x,n.z-s.player.z),diff=Math.atan2(Math.sin(desired-s.heading),Math.cos(desired-s.heading));await input([Math.abs(diff)>.06?(diff>0?'KeyD':'KeyA'):null,(Math.abs(diff)>1&&s.speed>5)||(conservative&&s.speed>8)?'KeyS':'KeyW'].filter(Boolean),100);if(!report.image&&(await state()).completed.length>=1){report.image=await p.screenshot();report.frame=await state();report.detailImage=await p.screenshot({clip:{x:120,y:440,width:860,height:280}});}}
 }
 };await playLoop(true);
 const won=await state();check('complete loop',won.mode==='won',won);report.completionSeconds=won.elapsed;report.runs=[{elapsed:won.elapsed,result:won.lastResult}];check('first record saved',won.bestSeconds===won.elapsed);await p.keyboard.press('KeyR');await tick(0);check('record survives restart',(await state()).bestSeconds===won.elapsed);await playLoop();const second=await state();check('second complete loop',second.mode==='won',second);check('record compares equivalent repeated run',second.lastResult.previousBest===won.elapsed&&second.bestSeconds===Math.min(won.elapsed,second.elapsed));if(start.kind==='rally')check('different braking approach improves lap',second.elapsed<won.elapsed&&second.lastResult.improvement>0);report.runs.push({elapsed:second.elapsed,result:second.lastResult});await p.reload();await p.waitForFunction(()=>!!window.render_game_to_text);await tick(0);check('record survives reload',(await state()).bestSeconds===second.bestSeconds);report.render=await p.evaluate(()=>__renderEvidence());check('ending still renders',report.render.triangles>0);await p.keyboard.press('KeyR');await tick(0);check('restart clears session',(await state()).completed.length===0&&(await state()).elapsed===0&&(await state()).carry===null);await tick(301000);check('idle failure',(await state()).mode==='lost');await p.keyboard.press('KeyR');await tick(0);check('restart after failure',(await state()).mode==='play');check('no browser errors',report.errors.length===0);report.status='PASS';if(report.image)report.screenshotHash=digest(report.image);if(report.detailImage)report.detailHash=digest(report.detailImage);signal?.removeEventListener('abort',abort);
 }catch(e){report.errors.push(e.message);}finally{await browser?.close();await new Promise(r=>server.close(r));}return report;
}
