import * as THREE from './vendor/three/three.module.js';
import {createCompositionEngine} from './kits/scene-kit.mjs';
const c=JSON.parse(document.querySelector('#composition').textContent),engine=createCompositionEngine(c),game=engine.n.arcade;
const reducedEffects=matchMedia('(prefers-reduced-motion: reduce)').matches;
const notify=(state,message)=>{if(parent!==window)parent.postMessage({type:'nexus-player',state,message},location.origin);};
let notifiedMode='';
const $=id=>document.getElementById(id),keys=new Set();let manual=false,last=performance.now(),accumulator=0,audio,overview=false;
const colors={lagoon:[0x081d32,0x42edce,0xffcc76],solar:[0x292539,0xffc76b,0x80dcff],violet:[0x16192f,0xc0a1ff,0x6af2d8],glacier:[0x102c3c,0x9feeff,0xffa780],coral:[0x281f38,0xff8f9d,0x94edda]}[c.palette];
const renderer=new THREE.WebGLRenderer({canvas:$('view'),antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;
const scene=new THREE.Scene();scene.background=new THREE.Color(colors[0]);scene.fog=new THREE.FogExp2(colors[0],.006);
const camera=new THREE.PerspectiveCamera(43,1,.1,240);camera.position.set(0,51,57);camera.lookAt(0,0,0);
scene.add(new THREE.HemisphereLight(0xcdeaff,0x293145,2.5));const sun=new THREE.DirectionalLight(0xffe6c5,3.5);sun.position.set(18,45,15);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-45,right:45,top:45,bottom:-45});sun.shadow.bias=-.0003;scene.add(sun);
const mat=(color,metalness=.25,roughness=.5)=>new THREE.MeshStandardMaterial({color,metalness,roughness});const stone=mat(0x35445c),edge=mat(0x16243a),accent=mat(colors[1]),gold=mat(colors[2]);accent.emissive=new THREE.Color(colors[1]);accent.emissiveIntensity=.3;
function mesh(geo,material,x,y,z){const m=new THREE.Mesh(geo,material);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;scene.add(m);return m;}
const points={home:c.home,...Object.fromEntries(c.nodes.map(n=>[n.id,n.position]))};
for(const [id,p] of Object.entries(points)){
 mesh(new THREE.CylinderGeometry(3.3,3.6,.75,6),stone,p.x,-.42,p.z);mesh(new THREE.CylinderGeometry(3.55,2.2,2.2,6),edge,p.x,-1.9,p.z);
 const rim=mesh(new THREE.TorusGeometry(2.9,.075,8,48),id==='home'?gold:accent,p.x,.08,p.z);rim.rotation.x=-Math.PI/2;
 for(let j=0;j<6;j++){const a=j*Math.PI/3;mesh(new THREE.BoxGeometry(.22,.6,.22),accent,p.x+Math.cos(a)*3,.2,p.z+Math.sin(a)*3);}
}
const bridges=[];for(const e of c.edges){const a=points[e.a],b=points[e.b],length=Math.hypot(a.x-b.x,a.z-b.z),angle=Math.atan2(b.x-a.x,b.z-a.z);const m=mesh(new THREE.BoxGeometry(2.8,.35,length),stone,(a.x+b.x)/2,-.23,(a.z+b.z)/2);m.rotation.y=angle;bridges.push({mesh:m,requires:e.requires});for(const side of [-1,1]){const rail=mesh(new THREE.BoxGeometry(.06,.08,length),accent,(a.x+b.x)/2+Math.cos(angle)*side*1.25,.04,(a.z+b.z)/2-Math.sin(angle)*side*1.25);rail.rotation.y=angle;}}
const actor=new THREE.Group();scene.add(actor);const body=new THREE.Mesh(new THREE.CapsuleGeometry(.35,.55,4,12),mat(0xeaf5ff,.6,.25));body.position.y=.75;body.castShadow=true;actor.add(body);const visor=new THREE.Mesh(new THREE.BoxGeometry(.45,.17,.22),accent);visor.position.set(0,1,.31);actor.add(visor);const halo=new THREE.Mesh(new THREE.TorusGeometry(.55,.055,6,32),gold);halo.rotation.x=Math.PI/2;halo.position.y=.06;actor.add(halo);
const objects=new Map(),labels=new Map();
for(const n of c.nodes){const p=n.position;const material=mat(colors[1],.6,.25);material.emissive=new THREE.Color(colors[1]);material.emissiveIntensity=.5;const obj=mesh(n.action==='carry'?new THREE.IcosahedronGeometry(.58,1):n.action==='hold'?new THREE.TorusGeometry(.8,.16,12,32):new THREE.OctahedronGeometry(.75),material,p.x,1.1,p.z);objects.set(n.id,obj);const label=document.createElement('span');label.className='world-label';label.textContent=n.id.slice(1)*1+1;$('labels').append(label);labels.set(n.id,label);}
// Renderer-neutral prerequisite relationships become visible tethers; they never own rule state.
for(const n of c.nodes)for(const id of n.requires){const a=points[id],b=n.position;const g=new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(a.x,.3,a.z),new THREE.Vector3(b.x,.3,b.z)]);const line=new THREE.Line(g,new THREE.LineDashedMaterial({color:0xffffff,transparent:true,opacity:.25,dashSize:.5,gapSize:.4}));line.computeLineDistances();scene.add(line);}
const stars=new THREE.BufferGeometry(),v=[];for(let i=0;i<130;i++){const a=i*2.399;v.push(Math.cos(a)*(45+i%35),-8-i%17,Math.sin(a)*(45+i%35));}stars.setAttribute('position',new THREE.Float32BufferAttribute(v,3));scene.add(new THREE.Points(stars,new THREE.PointsMaterial({color:colors[1],size:.12,transparent:true,opacity:.7})));
function resize(){renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();}addEventListener('resize',resize);resize();
let previous=0;function draw(){const s=game.snapshot();if(s.mode!==notifiedMode){notifiedMode=s.mode;notify(s.mode);}for(const bridge of bridges)bridge.mesh.visible=bridge.requires.every(x=>s.completed.includes(x));camera.position.set(overview?0:s.player.x,overview?51:23,overview?57:s.player.z+24);camera.lookAt(overview?0:s.player.x,0,overview?0:s.player.z-3);actor.position.set(s.player.x,s.player.y,s.player.z);const moving=keys.has('KeyW')||keys.has('ArrowUp')||keys.has('KeyD')||keys.has('ArrowRight');body.rotation.z=reducedEffects?0:(moving?Math.sin(s.elapsed*14)*.08:0);
 for(const n of s.nodes){const o=objects.get(n.id);o.visible=!n.complete;o.position.set(n.position.x,reducedEffects?1.15:1.15+Math.sin(s.elapsed*2+Number(n.id.slice(1)))*.12,n.position.z);if(s.carry===n.id)o.position.set(s.player.x,s.player.y+1.8,s.player.z);o.rotation.y=reducedEffects?0:s.elapsed*.5;o.material.emissiveIntensity=n.available?.8:.02;o.material.color.set(n.available?colors[1]:0x657085);const screen=new THREE.Vector3(n.position.x,2.5,n.position.z).project(camera);const label=labels.get(n.id);label.style.left=(screen.x*.5+.5)*innerWidth+'px';label.style.top=(-screen.y*.5+.5)*innerHeight+'px';label.textContent=(Number(n.id.slice(1))+1)+(n.complete?' ✓':!n.available?' ⏣':n.action==='carry'?' ◇':n.action==='hold'?' ◯ '+Math.round(n.progress/n.seconds*100)+'%':' ◆');label.style.opacity=n.complete?'.4':'1';label.hidden=screen.z>1||screen.z< -1||Math.abs(screen.x)>1||Math.abs(screen.y)>1;}
 $('time').textContent=Math.ceil(c.duration-s.elapsed);$('progress').textContent=c.required.filter(x=>s.completed.includes(x)).length+' / '+c.required.length;const near=s.nodes.find(n=>!n.complete&&Math.hypot(n.position.x-s.player.x,n.position.z-s.player.z)<2.3);$('hint').textContent=s.carry?'Carry core '+(Number(s.carry.slice(1))+1)+' to '+(c.nodes.find(n=>n.id===s.carry).receiver==='home'?'the landing pad':'anchor '+(Number(c.nodes.find(n=>n.id===s.carry).receiver.slice(1))+1))+' · E to transfer':near?(!near.available?'Locked · complete '+near.requires.map(x=>Number(x.slice(1))+1).join(', '):near.action==='hold'?'Hold E to restore · '+Math.round(near.progress/near.seconds*100)+'%':near.action==='carry'?'Press E to pick up this core':'Press E to activate this anchor'):c.required.every(x=>s.completed.includes(x))?'Reach '+(c.exit==='home'?'the landing pad':'anchor '+(Number(c.exit.slice(1))+1))+' to finish':s.message||'Follow the bridges · V for overview';$('overlay').hidden=s.mode==='play';$('overlay-title').textContent=s.mode==='title'?c.title:s.mode==='pause'?'Paused':s.mode==='won'?'Circuit complete':'Time expired';$('start').textContent=s.mode==='title'?'PLAY':s.mode==='pause'?'RESUME':'PLAY AGAIN';$('instructions').textContent=c.instructions;$('pause').textContent=s.mode==='pause'?'Resume':'Pause';
 if(s.interactions>previous&&$('sound').checked){audio??=new AudioContext();const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);o.frequency.value=520+s.completed.length*80;g.gain.setValueAtTime(.035,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.16);o.start();o.stop(audio.currentTime+.16);}previous=s.interactions;renderer.render(scene,camera);}
function advance(ms){if(!Number.isFinite(ms)||ms<0||ms>420000)throw Error('Invalid simulation interval');accumulator+=ms/1000;while(accumulator>=.05){game.step(.05,{x:Number(keys.has('KeyD')||keys.has('ArrowRight'))-Number(keys.has('KeyA')||keys.has('ArrowLeft')),z:Number(keys.has('KeyS')||keys.has('ArrowDown'))-Number(keys.has('KeyW')||keys.has('ArrowUp')),interact:keys.has('KeyE')||keys.has('Space')});accumulator-=.05;}draw();}
$('start').onclick=()=>{keys.clear();accumulator=0;audio?.resume();const s=game.snapshot();if(s.mode==='pause')game.pause();else{if(s.mode!=='title')game.reset();game.start();}draw();};$('pause').onclick=()=>{keys.clear();accumulator=0;game.pause();if(game.snapshot().mode==='play')audio?.resume();draw();};
addEventListener('keydown',e=>{if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();keys.add(e.code);if(e.repeat)return;if(e.code==='KeyV')overview=!overview;if(e.code==='Escape')game.pause();if(e.code==='KeyR'){game.reset();game.start();accumulator=0;}if(e.code==='KeyF'){if(document.fullscreenElement)document.exitFullscreen();else document.documentElement.requestFullscreen().catch(()=>{});}draw();});addEventListener('keyup',e=>keys.delete(e.code));const suspend=()=>{keys.clear();accumulator=0;if(game.snapshot().mode==='play')game.pause();audio?.suspend();draw();};addEventListener('blur',suspend);addEventListener('visibilitychange',()=>{if(document.hidden)suspend();});
window.render_game_to_text=()=>JSON.stringify(game.snapshot());window.advanceTime=ms=>{manual=true;advance(ms);};window.__renderEvidence=()=>({three:THREE.REVISION,drawCalls:renderer.info.render.calls,triangles:renderer.info.render.triangles,geometries:renderer.info.memory.geometries});
function frame(now){if(!manual&&!document.hidden&&game.snapshot().mode==='play')advance(Math.min(250,now-last));last=now;requestAnimationFrame(frame);}draw();notify('ready');requestAnimationFrame(frame);
