import {chromium} from 'playwright';
import {createServer} from 'node:http';
import {readFile} from 'node:fs/promises';
import path from 'node:path';
import {hash} from './model.mjs';
export async function serveFiles(root){const server=createServer(async(req,res)=>{try{if(req.url==='/favicon.ico'){res.writeHead(204);return res.end();}const p=decodeURIComponent(new URL(req.url,'http://localhost').pathname),file=path.resolve(root,'.'+p);if(!file.startsWith(path.resolve(root)+path.sep))throw Error('Bad path');res.setHeader('Content-Type',file.endsWith('.html')?'text/html':/\.(js|mjs)$/.test(file)?'text/javascript':file.endsWith('.png')?'image/png':'application/json');res.end(await readFile(file));}catch{res.writeHead(404);res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));return server;}
export async function review3d(root,id,{signal}={}){const server=await serveFiles(root);let browser;const report={status:'FAIL',checks:[],errors:[],method:'Chromium WebGL with software GPU; keyboard-controlled accelerated full loop'};const check=(name,pass,detail)=>{report.checks.push({name,pass,detail});if(!pass)throw Error(name+' '+JSON.stringify(detail??''));};
 try{browser=await chromium.launch({headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});const abort=()=>browser.close().catch(()=>{});signal?.addEventListener('abort',abort,{once:true});const p=await browser.newPage({viewport:{width:1100,height:780}});p.setDefaultTimeout(12000);p.on('pageerror',e=>report.errors.push(e.message));const origin='http://127.0.0.1:'+server.address().port;await p.route('**/*',r=>r.request().url().startsWith(origin+'/')?r.continue():r.abort());await p.goto(origin+'/'+id+'/index.html');await p.waitForFunction(()=>!!window.render_game_to_text);const state=()=>p.evaluate(()=>JSON.parse(render_game_to_text()));const tick=ms=>p.evaluate(ms=>advanceTime(ms),ms);await tick(0);check('title',(await state()).mode==='title');await p.click('#start');await tick(0);const initial=await state();await p.keyboard.down('ArrowUp');await tick(200);await p.keyboard.up('ArrowUp');check('movement',(await state()).player.z<initial.player.z);await p.keyboard.press('Escape');const t=(await state()).elapsed;await tick(1000);check('pause freezes active clock',(await state()).elapsed===t);await p.keyboard.press('KeyR');await tick(0);check('restart clears state',(await state()).completed.length===0);
 let current='home';const st=await state(),points={home:st.home,...Object.fromEntries(st.nodes.map(n=>[n.id,n.position]))};
 const go=async target=>{for(let i=0;i<400;i++){if(signal?.aborted)throw Error('Cancelled');const s=await state();if(s.mode==='won'&&st.required.every(x=>s.completed.includes(x)))return;if(s.mode!=='play')throw Error('Ended before route completed: '+s.mode);const dx=target.x-s.player.x,dz=target.z-s.player.z;if(Math.hypot(dx,dz)<.45)return;const vx=Math.abs(dx)>.18?Math.sign(dx):0,vz=Math.abs(dz)>.18?Math.sign(dz):0,keys=[vx>0?'ArrowRight':vx<0?'ArrowLeft':null,vz>0?'ArrowDown':vz<0?'ArrowUp':null].filter(Boolean);for(const k of keys)await p.keyboard.down(k);await tick(Math.hypot(dx,dz)<1?50:100);for(const k of keys)await p.keyboard.up(k);}throw Error('Route stalled');};
 const route=async to=>{const q=[[current]],seen=new Set([current]);let found;while(q.length){const a=q.shift();if(a.at(-1)===to){found=a;break;}for(const e of st.edges){const n=e.a===a.at(-1)?e.b:e.b===a.at(-1)?e.a:null;if(n&&!seen.has(n)){seen.add(n);q.push([...a,n]);}}}if(!found)throw Error('Unreachable');for(let i=1;i<found.length;i++){const a=points[found[i-1]],b=points[found[i]],steps=Math.ceil(Math.hypot(b.x-a.x,b.z-a.z)/1.2);for(let j=1;j<=steps;j++){if((await state()).mode==='won'&&to===st.exit)break;await go({x:a.x+(b.x-a.x)*j/steps,z:a.z+(b.z-a.z)*j/steps});}}current=to;};
 await go(points.home);
 // Locked action is tested before legitimate completion where the graph has prerequisites.
 const locked=st.nodes.find(n=>n.requires.length);if(locked)check('prerequisite initially locked',!locked.available);
 for(const n of st.nodes.filter(n=>st.required.includes(n.id))){await route(n.id);await p.keyboard.down('KeyE');await tick(n.action==='hold'?(n.seconds+.15)*1000:100);await p.keyboard.up('KeyE');if(n.action==='carry'){check('cargo attaches',(await state()).carry===n.id);await route(n.receiver);await p.keyboard.down('KeyE');await tick(100);await p.keyboard.up('KeyE');check('cargo transfers',(await state()).carry===null);}check('objective '+n.id,(await state()).completed.includes(n.id));if(!report.image){await tick(0);report.frame=await state();report.image=await p.screenshot();report.screenshotHash=hash(report.image);}else if(!report.overviewImage&&(await state()).completed.length>=Math.ceil(st.required.length/2)&&(await state()).mode==='play'){await p.keyboard.press('KeyV');await tick(0);report.overviewImage=await p.screenshot();report.overviewHash=hash(report.overviewImage);await p.keyboard.press('KeyV');await tick(0);}}
 await route(st.exit);await tick(50);check('complete playable loop',(await state()).mode==='won');report.completionSeconds=(await state()).elapsed;check('WebGL rendered',(await p.evaluate(()=>__renderEvidence())).triangles>1000);report.render=await p.evaluate(()=>__renderEvidence());await p.keyboard.press('KeyR');await tick(0);await tick(301000);check('idle fails',(await state()).mode==='lost'&&(await state()).completed.length===0);await p.keyboard.press('KeyR');await tick(0);check('reset after failure',(await state()).mode==='play'&&(await state()).elapsed===0&&(await state()).carry===null);check('no browser errors',!report.errors.length);report.status='PASS';signal?.removeEventListener('abort',abort);
 }catch(e){report.errors.push(e.message);}finally{await browser?.close();server.closeAllConnections?.();await new Promise(r=>server.close(r));}return report;}
