import {mkdir,readFile,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {compileConceptRecipe} from './concept-recipe.mjs';
import {compileSceneRecipe} from './scene-recipe.mjs';
import {compilePlayableScene,structuralSceneSignature} from './scene-spec.mjs';
import {reviewScene} from './scene-review.mjs';
import {preflightScene} from './scene-preflight.mjs';
import {Models} from './model.mjs';
import {sceneTextContracts,sceneImageSchema,sceneImageVerdict,playerDetailSchema} from './scene-model-contracts.mjs';
import {atomicJSON,writerLease,deadline,contracts,digest} from './factory.mjs';
import {build,experiments,fingerprint} from './assembly.mjs';
import {indexPreview} from './library.mjs';
import {assertAllowedText} from './text-policy.mjs';
export function validateSceneRetry(prior,profile,ruleVersion,reason){
 const intent=p=>digest({seed:p.scene.behavior.seed,specificIntent:p.scene.behavior.specificIntent,decisions:p.scene.behavior.decisions,conceptBranches:p.scene.behavior.conceptBranches,durationSeconds:p.scene.session.durationSeconds});
 if(prior.version!==4||!['FAIL','NEEDS_REVIEW','CANCELLED'].includes(prior.status)||prior.ruleVersion!==ruleVersion||!Number.isFinite(prior.started)||prior.deadline!==prior.started+1500000||intent(prior.profile)!==intent(profile))throw Error('Retry changed frozen intent, selections, clock or acceptance rules');
 if(prior.profileHash!==digest(profile)&&(typeof reason!=='string'||reason.trim().length<10||reason.length>300))throw Error('Changed profile requires an explicit repair reason');
 assertAllowedText(reason);return {priorProfileHash:prior.profileHash,reason:reason??null};
}
export async function generateScene({id,profile,recipe,conceptRecipe,retryOf,repairReason,signal,onProgress=()=>{}}){
 const validId=x=>typeof x==='string'&&/^[a-zA-Z0-9][a-zA-Z0-9_-]{0,70}$/.test(x);if(!validId(id)||retryOf&&!validId(retryOf))throw Error('Invalid scene ID');
 const startingSourceHash=await fingerprint(),spec=await contracts();if([recipe,profile,conceptRecipe].filter(x=>x!==undefined).length!==1)throw Error('Use exactly one recipe, concept recipe or explicit profile');const conceptExpanded=conceptRecipe===undefined?null:compileConceptRecipe(spec.catalog,conceptRecipe);if(conceptExpanded)recipe=conceptExpanded.recipe;const expanded=conceptExpanded??(recipe===undefined?null:compileSceneRecipe(spec.catalog,recipe));profile=expanded?.profile??profile;const compiled=expanded?.compiled??compilePlayableScene(spec.catalog,profile),admittedAt=Date.now(),release=await writerLease(id);let s;
 try{
  if((await contracts()).hash!==spec.hash)throw Error('Contract changed before scene admission');
  for(const sourceId of recipe?.lineage?.sourceIdeas??[]){const source=JSON.parse(await readFile(path.join(experiments,sourceId,'spine.json')));if(source.id!==sourceId||!['FAIL','NEEDS_REVIEW','CANCELLED'].includes(source.status))throw Error('Recipe lineage requires a terminal development idea');}
  let prior,revision=null;if(retryOf){prior=JSON.parse(await readFile(path.join(experiments,retryOf,'spine.json')));revision=validateSceneRetry(prior,profile,spec.hash,repairReason);}
  await mkdir(path.join(experiments,id));if(expanded)await writeFile(path.join(experiments,id,conceptExpanded?'concept-recipe.json':'recipe.json'),JSON.stringify(conceptRecipe??recipe),{flag:'wx'});const started=prior?.started??admittedAt;s={version:4,purpose:'foundation-pilot',id,ideaId:prior?.ideaId??id,retryOf:retryOf??null,started,deadline:prior?.deadline??started+1500000,revisionCreated:Date.now(),seed:profile.scene.behavior.seed,recipe:expanded?{recipeHash:expanded.recipeHash,trace:expanded.trace,lineage:recipe.lineage??null,sourceFile:conceptExpanded?'concept-recipe.json':'recipe.json',...(conceptExpanded?{conceptRecipeHash:conceptExpanded.conceptRecipeHash,conceptRoll:{seed:conceptExpanded.conceptRoll.seed,catalogHash:conceptExpanded.conceptRoll.catalogHash,inputHash:conceptExpanded.conceptRoll.inputHash,decisions:conceptExpanded.conceptRoll.decisions},matchedFragments:conceptExpanded.matchedFragments}:{})}:null,profileHash:compiled.profileHash,profile,revision,compilation:{catalogHash:compiled.compilation.catalogHash,bindingHash:compiled.compilation.bindingHash,requiredWitnesses:compiled.compilation.requiredWitnesses,unresolvedGamePoints:compiled.compilation.unresolvedGamePoints,sceneLayers:compiled.compilation.sceneLayers},composition:compiled.composition,calls:[],status:'PLANNING',ruleVersion:spec.hash,admissionSourceHash:startingSourceHash};
  const guard=deadline(s,signal),combined=AbortSignal.any([AbortSignal.timeout(guard.remaining()),...(signal?[signal]:[])]),save=async()=>{guard.check();await atomicJSON(path.join(experiments,id,'spine.json'),s);onProgress({id,status:s.status,elapsedMs:Date.now()-started});};await save();const models=new Models(s,save,{signal:combined});await models.check();const textContracts=sceneTextContracts(s.composition);
  s.status='PREFLIGHT';await save();s.preflight=await preflightScene(compiled.composition.runtime,compiled.validationPlan,{signal:combined,deadlineAt:s.deadline,witnesses:compiled.compilation.requiredWitnesses});await save();if(s.preflight.status!=='PASS')throw Error('Runtime preflight: '+s.preflight.error);s.status='PLANNING';await save();
  s.plan=await models.askValidated('planner','scene-plan','Use choice 0 for the supported composition. Return its supplied specificIntent exactly as intent. Gameplay is already compiled; preserve its actions and objective. '+JSON.stringify({specificIntent:profile.scene.behavior.specificIntent,preparedInterpretation:profile.scene.behavior.preparedInterpretation,guidance:profile.guidance??[],domains:profile.presentation.instances.map(n=>n.label),choice:0}),textContracts.planner,500);
s.status='WRITING';s.editorial=await models.askValidated('writer','scene-write','Choose one supplied title. Preserve the supplied palette selected by the composition. Return the supplied goal exactly as tagline. These choices describe implemented behavior. '+JSON.stringify({goal:s.composition.goal,titles:textContracts.titles,palette:s.composition.presentation.theme}),textContracts.writer,350);
  const final=compilePlayableScene(spec.catalog,profile,{title:s.editorial.title,theme:s.editorial.palette});s.composition=final.composition;s.status='ASSEMBLING';await save();Object.assign(s,await build(s.composition,id));if(s.sourceHash!==s.admissionSourceHash)throw Error('Source changed after admission');s.status='TESTING';await save();s.browser=await reviewScene(experiments,id,final.validationPlan,{signal:combined});
  const image=s.browser.image,before=s.browser.initialImage,playerImage=s.browser.playerImage,initialPlayerImage=s.browser.initialPlayerImage;delete s.browser.image;delete s.browser.initialImage;delete s.browser.playerImage;delete s.browser.initialPlayerImage;if(playerImage)await writeFile(path.join(experiments,id,'player-detail.png'),playerImage,{flag:'wx'});if(initialPlayerImage)await writeFile(path.join(experiments,id,'initial-player-detail.png'),initialPlayerImage,{flag:'wx'});if(image)await writeFile(path.join(experiments,id,'review.png'),image,{flag:'wx'});if(before)await writeFile(path.join(experiments,id,'initial.png'),before,{flag:'wx'});guard.check();if(s.browser.status!=='PASS')throw Error(s.browser.errors.join('; '));
  s.status='VISUAL_REVIEW';await save();s.visualFrames=[];for(const [frameId,bytes,detailBytes]of [['initial',before,initialPlayerImage],['consequence',image,playerImage]]){const facts=await models.askValidated('writer','scene-review','Inspect this actual image. The player is the cyan capsule, marked YOU when space permits. Report only geometry visibility, label readability and player visibility using the allowed values. Use uncertain when the frame is insufficient. Do not infer gameplay, reachable routes, objectives or uniqueness. '+JSON.stringify({frameId,view:s.composition.presentation.camera}),sceneImageSchema(s.composition),180,bytes);let detail=null;const resolvedFacts={...facts};if(facts.player==='uncertain'&&facts.geometry==='visible'&&facts.labels==='readable'&&detailBytes){detail=await models.askValidated('writer','scene-player-detail','This is an unmodified crop centered on the actual player screen bounds. Is the cyan player object visible near the center? The YOU label may also appear. Report only visible, not_visible or uncertain. Do not infer gameplay.',playerDetailSchema,80,detailBytes);if(detail.subject==='visible')resolvedFacts.player='visible';}const result=sceneImageVerdict(s.composition,resolvedFacts);s.visualFrames.push({frameId,imageHash:digest(bytes),facts,result,...(detail?{playerDetail:{imageHash:digest(detailBytes),result:detail}}:{})});await save();if(result.verdict!=='PASS')throw Error('Visual review '+frameId+': '+JSON.stringify(facts));}
  guard.check();if(s.sourceHash!==await fingerprint())throw Error('Source changed during scene generation');s.signature=structuralSceneSignature(s.composition,final.validationPlan);s.previewVerdict='PASS';s.status='NEEDS_REVIEW';const missing=['catalog eligibility','comparative novelty','replay tradeoff','presentation and audio','target-device performance','human comprehension'];const causal=s.preflight.conceptObservations?.length&&s.preflight.domainAblations?.length&&s.preflight.checks.filter(c=>c.name.startsWith('concept changes during successful play ')||c.name.startsWith('removing domain prevents a demonstrated route ')).every(c=>c.pass);if(!causal)missing.splice(1,0,'independent concept causality');s.acceptance={verdict:'NEEDS_REVIEW',missing};s.elapsedMs=Date.now()-started;s.completed=Date.now();await save();await indexPreview(id);return s;
 }catch(e){if(!s)throw e;s.status=signal?.aborted?'CANCELLED':'FAIL';s.error=e.message;s.elapsedMs=Date.now()-s.started;await atomicJSON(path.join(experiments,id,'spine.json'),s);onProgress({id,status:s.status,error:s.error});return s;}finally{await release();}
}
