import {createSceneEngine} from './kits/scene-runtime.mjs';
import {createSceneView} from './kits/scene-view.mjs';
const $=id=>document.getElementById(id),c=JSON.parse($('composition').textContent),key='nexus-scene-best:'+new URL(import.meta.url).pathname+':'+c.replay.recordKey;
let best=null;try{const n=Number(localStorage.getItem(key));if(Number.isFinite(n)&&n>0&&n<=c.runtime.session.durationSeconds)best=n;}catch{}
const game=createSceneEngine(c.runtime,{bestSeconds:best}).n.arcade,view=createSceneView($('view'),c),keys=new Set();let manual=false,last=performance.now(),acc=0,lastMode='',lastEvent='',audio,pendingInteractions=0,interactionHigh=false;
const definitions=new Map(c.runtime.domainGraph.instances.map(n=>[n.id,n])),labels=new Map(c.presentation.nodes.map(n=>[n.id,n.label]));
function clearInput(){keys.clear();pendingInteractions=0;interactionHigh=false;acc=0;}
function notify(state,message){if(parent!==window)parent.postMessage({type:'nexus-player',state,message},location.origin);}
function draw(){const s=game.snapshot();view.render(s);if(lastMode!==s.mode){lastMode=s.mode;if(s.mode!=='play')clearInput();notify(s.mode);}if(s.mode==='won'&&s.bestSeconds!==best){try{localStorage.setItem(key,String(s.bestSeconds));best=s.bestSeconds;}catch{}}
 const progress=c.presentation.hud.map(id=>{const d=s.domainState[id],n=definitions.get(id);return labels.get(id)+' '+(n.capability==='flowStore'?Math.round(d.volume)+'/'+n.settings.capacity+' L':n.capability==='reservoir'?Math.round(d.fill*100)+'%':d.completed.length+'/'+n.settings.nodes.length);}).join(' · ');
 $('title').textContent=c.title;$('counter-label').textContent='';$('progress').textContent=progress;$('progress').style.fontSize='16px';$('time').textContent=Math.ceil(c.runtime.session.durationSeconds-s.elapsed);$('hint').textContent=(c.runtime.movement.adapter==='steering'?Math.round(s.speed*3.6)+' km/h':'E interact')+' · Time '+s.elapsed.toFixed(1)+'s · Best '+(s.bestSeconds===null?'—':s.bestSeconds.toFixed(2)+'s');
 $('overlay').hidden=s.mode==='play';$('overlay-title').textContent=s.mode==='title'?c.title:s.mode==='pause'?'Paused':s.mode==='won'?'Complete!':s.elapsed>=c.runtime.session.durationSeconds?'Time expired':'Limit reached';$('instructions').textContent=s.mode==='won'?'Time '+s.lastResult.seconds.toFixed(2)+'s. '+c.replay.reason:c.goal;$('start').textContent=s.mode==='pause'?'RESUME':s.mode==='title'?'PLAY':'PLAY AGAIN';$('pause').textContent=s.mode==='pause'?'Resume':'Pause';document.querySelector('#instructions+p').textContent=c.controls;
 const event=s.events.at(-1),identity=JSON.stringify(event);if(event&&identity!==lastEvent&&['turned','delivered','checkpoint','won'].includes(event.type)&&$('sound').checked){audio??=new AudioContext();const tone=audio.createOscillator(),gain=audio.createGain();tone.connect(gain);gain.connect(audio.destination);tone.frequency.value=event.type==='won'?740:440;gain.gain.setValueAtTime(.035,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.15);tone.start();tone.stop(audio.currentTime+.15);}lastEvent=identity;
}
function advance(ms){if(!Number.isFinite(ms)||ms<0||ms>601000)throw Error('Invalid simulation interval');acc+=ms/1000;while(acc>=.05){const interact=!interactionHigh&&pendingInteractions>0;if(interact)pendingInteractions--;interactionHigh=interact;game.step(.05,{x:Number(keys.has('KeyD')||keys.has('ArrowRight'))-Number(keys.has('KeyA')||keys.has('ArrowLeft')),z:Number(keys.has('KeyS')||keys.has('ArrowDown'))-Number(keys.has('KeyW')||keys.has('ArrowUp')),interact});acc-=.05;}draw();}
function resume(){clearInput();audio?.resume();if(game.snapshot().mode==='pause')game.pause();else{game.reset();game.start();lastEvent='';}draw();}
function pause(){clearInput();game.pause();draw();}
function suspend(){clearInput();if(game.snapshot().mode==='play')game.pause();audio?.suspend();draw();}
$('start').onclick=resume;$('pause').onclick=pause;addEventListener('keydown',e=>{if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(e.repeat||keys.has(e.code))return;if(['KeyE','Space'].includes(e.code)&&game.snapshot().mode==='play'&&!keys.has('KeyE')&&!keys.has('Space'))pendingInteractions++;keys.add(e.code);if(e.code==='Escape')pause();if(e.code==='KeyR'){game.reset();game.start();clearInput();lastEvent='';}if(e.code==='KeyF'){if(document.fullscreenElement)document.exitFullscreen?.();else document.documentElement.requestFullscreen?.();}draw();});addEventListener('keyup',e=>keys.delete(e.code));addEventListener('blur',suspend);addEventListener('visibilitychange',()=>{if(document.hidden)suspend();});addEventListener('resize',()=>{view.resize();draw();});addEventListener('pagehide',e=>{if(e.persisted)suspend();else{view.dispose();audio?.close();}});addEventListener('pageshow',e=>{if(e.persisted){clearInput();last=performance.now();view.resize();draw();}});
window.render_game_to_text=()=>JSON.stringify({...game.snapshot(),objective:c.goal,coordinates:'x right, y up, z south; metres'});window.advanceTime=ms=>{manual=true;advance(ms);};window.__renderEvidence=view.evidence;
draw();notify('ready');function frame(now){if(!manual&&!document.hidden&&game.snapshot().mode==='play')advance(Math.min(250,now-last));last=now;requestAnimationFrame(frame);}requestAnimationFrame(frame);
